name: Build Endgame 2048

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Mingw
        run: choco install make mingw
      - name: Build
        run: |
          cd resource/raylib/src && mingw32-make PLATFORM=PLATFORM_DESKTOP RAYLIB_RELEASE_PATH="."
          cd ../../.. && mingw32-make CC=gcc
      - name: Cleanup raylib source
        run: |
          if (Test-Path resource/raylib) {
            Remove-Item -Recurse -Force resource/raylib
          }
        shell: pwsh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: endgame-windows
          path: |
            endgame.exe
            resource/
            README.md

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Build
        run: make
      - name: Cleanup raylib source
        run: rm -rf resource/raylib
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: endgame-linux
          path: |
            endgame
            resource/
            README.md
